### ISSUE TITLE
웹사이트 이름 정하기

### ISSUE THREAD

**Issue by Jeeyool-Min** [Jeeyool/EzenFinal#1]
생각나는대로 올려주세요

**Comment by ljy950113** [comment]
M.C.L.P 
민최이박

이름 앞글자를 따봤습니다..

**Comment by apple6487** [comment]
헐 저도 MCLP 이런식으로 앞글자 따와서 생각했는데
clamp 이 단어가 있더라구요
단어 의미는.. 솔직히 저희 프로그램이랑 안맞는데 일단 적어봅니댜,,,

단어 뜻은 여기서 보세유
https://en.dict.naver.com/#/search?query=clamp&range=all

**Comment by Jeeyool-Min** [comment]
clockIneasy
다른 외국 근태관리 프로그램에서 훔쳐왔어요ㅎㅎ

**Comment by apple6487** [comment]
clock on : (시간기록계에) 출근 카드를 찍다 는 어떨까욤
로고는 clockOn 이런식으로 하면 괜춘할것같아요
지율씨꺼 보고 갑자기 생각나서 올려요~
